fixed: in empty dir it shows message, and context menu is enabled. solves #113
cockpit-project/cockpit-navigator pull request #159
Opened 2023-12-05 10:30 UTC by ashutosh7i

i have solved this issue-
https://github.com/cockpit-project/cockpit-navigator/issues/113

GIF of progress-
![Screencast from 04-12-23 06 43 07 PM IST](https://github.com/cockpit-project/cockpit-navigator/assets/44861896/e71212af-283b-4062-a03b-63ff464af21f)

=> My changes
1. It checks for directory contents beforehand, and works accordingly, if dir is empty it sets the space to 200px with a message "Directory is Empty" for user.
2. The context menu can be envoked from anywhere in the area.
3. works in grid as well as other mode.

2024-01-22 16:28 UTC, jelly requested changes
Sorry for the very long delay, I've posted some review comments.

2024-01-22 16:28 UTC, jelly commented on src/navigatorContextMenu.jsx
> +        if (parent && !isEmptyDirectory) {
This check does not make a ton of sense as it checks the same variable twice.

2024-01-22 16:28 UTC, jelly commented on src/app.jsx
> +                    Directory is empty
This should be `{ _("Directory is empty")  }` as it needs to be translated.

2024-01-22 16:28 UTC, jelly commented on src/app.jsx
> +                            )
This makes not a lot of sense, it is already behind a `if (isGrid)` on line 627.

2024-01-22 16:28 UTC, jelly commented on src/app.jsx
> +            </CardBody>
Same as above, isGrid is always false here

2024-01-23 10:10 UTC, garrett commented
I commented about this @ 
- https://github.com/cockpit-project/cockpit-navigator/issues/113#issuecomment-1840520137
- https://github.com/cockpit-project/cockpit-navigator/issues/113#issuecomment-1842533288

I think this PR, when it lands, would close #113.

2024-02-01 18:16 UTC, ashutosh7i commented
Sorry for a long delay from my side, i went to a hackathon (won it though😁) now i am working on changes.

2024-03-15 08:48 UTC, jelly commented
Sorry this has been meanwhile fixed in https://github.com/cockpit-project/cockpit-navigator/commit/fc8a58ffec22cd2b713e0a609c5bdabfe4762be1

2024-03-15 08:48 UTC, closed without merging