Dialogs medium variant
cockpit-project/cockpit-navigator pull request #202
Opened 2024-01-24 13:54 UTC by jelly

Go smoll

![image](https://github.com/cockpit-project/cockpit-navigator/assets/67428/bd507435-c1fe-489c-b1f0-09795837101c)

2024-01-25 10:07 UTC, allisonkarlitskaya commented
Can you give before & after screenshots?  I think we might actually want small here — that's what I ended up using for the properties (eg. permissions) dialog.

2024-01-25 10:53 UTC, jelly commented
> Can you give before & after screenshots? I think we might actually want small here — that's what I ended up using for the properties (eg. permissions) dialog.

We don't want what it was for sure that takes up the full width however, I see we now have small and medium mixed.

2024-01-26 08:13 UTC, marusak commented
I did some digging and we use in cockpit 11 modals with `small`, around 30 with `medium` and no `large`. In podman we always use `medium`. In machines we use 17 modal with `medium` and 11 with `small`.

We also have `pkg/lib/cockpit-components-dialog.jsx:            <Modal position="top" variant={this.props.variant || "medium"}` -  so we default to medium.

So I thing we should be using `medium` by default. Some of the `small` ones might be just wrong usage but maybe some of them are there for a good reason. We can verify with @garrett or just go with medium everywhere.

2024-01-29 15:02 UTC, garrett requested changes
So I think this PR is mostly correct. However, we probably do need a longer width for the create link modal (medium), as it may require a full path. The others should be small.

---

General Cockpit unwritten* rule for modal sizing:

We should generally go with small, unless the forms require more width, then we go with medium. And if they need large, then they most likely need a redesign as they're probably too complex. (There can be exceptions.)

Reasoning: It's easier to read narrower text and elements. Generally, [optimal line width is between 50 to 75 characters](https://baymard.com/blog/line-length-readability). The small modal width is roughly 70 characters wide. (It's sometimes a little longer and sometimes shorter, depending on word length.)

However, when you do need to enter longer content, such as full paths, you need extra space, so sometimes we need to go longer and bump up to medium size.

(* I just wrote it here, so I guess it's a written rule now? :wink:)

2024-01-29 16:38 UTC, KKoukiou commented on src/fileActions.jsx
> +          variant={ModalVariant.medium}
You say small in the commit message but use medium

2024-01-30 08:26 UTC, allisonkarlitskaya commented
I think this is @garrett's to review.

2024-01-30 09:01 UTC, garrett commented
Why was create directory changed to medium and the create link left as small? Shouldn't it be the opposite? Create directory is contextual to your current location and shouldn't be long (unless it accepts sub-directories and does a `mkdir -p`), whereas link could be absolute and therefore could be long.

2024-02-02 09:23 UTC, jelly commented
> Why was create directory changed to medium and the create link left as small? Shouldn't it be the opposite? Create directory is contextual to your current location and shouldn't be long (unless it accepts sub-directories and does a `mkdir -p`), whereas link could be absolute and therefore could be long.

Ok, in that case rename should also be small.

2024-02-08 16:57 UTC, garrett approved these changes
Thanks!

2024-02-09 16:06 UTC, martinpitt requested changes

2024-02-09 16:06 UTC, martinpitt commented on src/fileActions.jsx
> +          variant={ModalVariant.medum}
as is this is `undefined`, it means that it's happy with the default value?

2024-02-09 16:29 UTC, martinpitt approved these changes

2024-02-09 16:30 UTC, merged