Rename to 'File manager'
cockpit-project/cockpit-navigator pull request #291
Opened 2024-02-29 14:50 UTC by marusak

This also requires to rename this repo. Please debate :)

2024-02-29 14:52 UTC, KKoukiou approved these changes

2024-02-29 14:54 UTC, KKoukiou requested changes

2024-02-29 14:54 UTC, KKoukiou commented on test/check-application
> +        self.enter_file-manager()
I think you need underscore here.

2024-02-29 14:56 UTC, martinpitt commented
I'm ok with changing the name. Bots [dislike some syntax thing](https://cockpit-logs.us-east-1.linodeobjects.com/pull-291-20240229-145049-9e09551e-debian-testing/log.html).

What I don't like is the "manager" bit (I know, that's odd , with this PR coming from you @marusak :grin: ). We don't call our pages "accounts manager", "VM manger", or "container manager". So if we rename it, I'd rather go with "cockpit-files". But then it supports directories too :grin: 

This is further complicated by navigator being an existing thing in Fedora and other places, so this would need to grow some `Obsoletes:`, `Replaces:` and such.

So in the end

 - Naming is hard
 - Is it really worth it? Where is this coming from?

2024-02-29 15:11 UTC, marusak commented
>What I don't like is the "manager" bit (I know, that's odd , with this PR coming from you @marusak 😁 )

Should I take this personally? :rofl: 

> We don't call our pages "accounts manager", "VM manger", or "container manager". So if we rename it, I'd rather go with "cockpit-files". But then it supports directories too 😁

Good point!

> This is further complicated by navigator being an existing thing in Fedora and other places, so this would need to grow some Obsoletes:, Replaces: and such.

I want to introduce that in separate PR. Actually, this makes it easier as if we want to start releasing into existing packages we need some rights to do that.

> Is it really worth it? Where is this coming from?

There was already question from someone what is "navigator". It is not clear from this repo (go to https://github.com/cockpit-project/cockpit-navigator and figure out what it does :)) but also we call it 'File browser' in the menu so the link between name and package name already is lost.

> Naming is hard

'File browser'? :) 
'Files'?

2024-03-02 14:43 UTC, allisonkarlitskaya commented
2¢: The name of the article for (this concept) on Wikipedia is "File manager" — I don't know any gut-feeling source more authoritative than that.  Files is a fine name.  Otherwise, looking at the names of various software that does this sort of thing (ie: appeal to user familiarity), one can find a lot of repeated uses of the words "commander" (particularly for the old-school dual-pane ones), "explorer", and "tree".  Of those three, I think "cockpit-explorer" is the only one that vaguely fits, even if "cockpit-commander" sounds kinda l33t.

Explorer has the benefit of being familiar to nearly all Windows users as well as many Android users (as nearly all of the most popular file manager apps there have names like "Mixplorer", "Solid Explorer", "X-plore", "FX Explorer", etc.) ((source: the reddit post which was the first google hit))

2024-03-04 10:03 UTC, jelly commented
Cockpit-Files also SGTM

2024-03-11 17:22 UTC, garrett commented
I support renaming.

It's a general design rule of thumb to really avoid "manager" in interfaces.

I'm fine with "Cockpit-Files" as the project name and "Files" in the sidebar. It makes sense, especially since we don't use "Accounts manager" / "Accounts browser" or any other "manager" or "browser" elsewhere — and nor should we. 

(Of course, the "browser" itself is really Cockpit Client, Firefox, Chrome, Safari, etc., right? :wink:)

2024-03-14 13:16 UTC, marusak commented
Ok, renamed to Files. @martinpitt @allisonkarlitskaya @KKoukiou @garrett We all agree? :) 

It has fresh conflict, I will resolve but we need to land quickly then as it is easy to get conflicts

2024-03-15 04:56 UTC, martinpitt commented
I'm fine with "Cockpit Files", thanks!

2024-03-15 07:45 UTC, jelly commented
Same, we do need to update the localStorage settings after https://github.com/cockpit-project/cockpit-navigator/pull/3226

2024-03-15 09:41 UTC, jelly requested changes

2024-03-15 09:41 UTC, jelly commented on packaging/debian/control
> +Package: cockpit-files
No replaces?

2024-03-15 09:41 UTC, jelly commented on packaging/cockpit-files.spec.in
> +Name: cockpit-files
This should replace navigator no?

2024-03-15 09:42 UTC, jelly commented
This is a new flake https://cockpit-logs.us-east-1.linodeobjects.com/pull-291-7e9d6b0f-20240315-093324-fedora-39-devel/log.html#10

2024-03-18 07:42 UTC, marusak commented
@jelly retried. I have possible fix I will push in separate PR.

2024-03-18 09:12 UTC, allisonkarlitskaya approved these changes

2024-03-18 09:15 UTC, martinpitt submitted a review, later dismissed

2024-03-18 11:05 UTC, KKoukiou submitted a review, later dismissed

2024-03-18 12:06 UTC, jelly commented on src/files-folder-view.tsx
> +    selected: FilesFileInfo[],
This makes no sense :)

2024-03-18 12:07 UTC, jelly commented on src/manifest.json
> +			"matches": ["files", "files", "explorer", "filesystem"]
files twice now

2024-03-18 14:38 UTC, jelly approved these changes

2024-03-18 15:20 UTC, merged